import React,{useEffect,useState} from 'react';
import {Megaphone,Plus,Send,Pencil,Trash2,Users} from 'lucide-react';
import {Dialog,toast,confirmAction} from '@pixellift/ui';
import {adminApi} from '../services/api';
import {useAdminAuth} from '../context/AdminAuthContext';
export function NotificationsPage(){
 const {hasPermission}=useAdminAuth(),canWrite=hasPermission(['Admin']);
 const [items,setItems]=useState<any[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[editing,setEditing]=useState<any>(null),[busy,setBusy]=useState(false);
 const [title,setTitle]=useState(''),[content,setContent]=useState(''),[target,setTarget]=useState('All');
 const load=async()=>{try{setItems(await adminApi.getNotifications());setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const open=(n:any)=>{setEditing(n);setTitle(n.title||'');setContent(n.content||'');setTarget(n.target||'All');};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{const payload={title:title.trim(),content:content.trim(),target};if(editing.id)await adminApi.updateNotification(editing.id,payload);else await adminApi.broadcastNotification(payload);toast.success('Pengumuman tersedia di dashboard pengguna.');setEditing(null);await load();}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}};
 const remove=async(n:any)=>{if(!await confirmAction('Hapus pengumuman "'+n.title+'"?'))return;try{await adminApi.deleteNotification(n.id);toast.success('Pengumuman dihapus.');await load();}catch(e){toast.error((e as Error).message);}};
 return <div className="admin-page"><div className="admin-page-heading"><div><span className="studio-eyebrow">KEEP EVERYONE UPDATED</span><h1>Pengumuman</h1><p>Informasikan pembaruan langsung melalui dashboard pengguna.</p></div>{canWrite&&<button className="pl-btn pl-btn-primary" onClick={()=>open({})}><Plus size={17}/>Buat pengumuman</button>}</div>
 {loading?<div className="pl-skeleton"/>:error?<div className="pl-empty"><p>{error}</p><button className="pl-btn" onClick={load}>Coba lagi</button></div>:!items.length?<div className="pl-empty pl-card"><Megaphone size={36}/><h3>Belum ada pengumuman</h3><p>Kabar produk dan informasi baru akan muncul di sini.</p></div>:<div className="admin-notification-list">{items.map(n=><article className="pl-card" key={n.id}><div className="notification-symbol"><Megaphone size={21}/></div><div className="notification-copy"><div className="pl-toolbar"><span className="pl-badge">{n.target==='All'?'Semua pengguna':n.target}</span><small>{new Date(n.created_at).toLocaleDateString('id-ID')}</small></div><h3>{n.title}</h3><p>{n.content}</p><small><Users size={13}/> {n.sent_count} akun dalam target saat dibuat</small></div>{canWrite&&<div className="admin-card-actions"><button className="pl-icon-btn" aria-label={'Edit '+n.title} onClick={()=>open(n)}><Pencil size={16}/></button><button className="pl-icon-btn" aria-label={'Hapus '+n.title} onClick={()=>remove(n)}><Trash2 size={16}/></button></div>}</article>)}</div>}
 {editing&&<Dialog title={editing.id?'Edit pengumuman':'Pengumuman baru'} onClose={()=>{if(!busy)setEditing(null);}}><form className="pl-form" onSubmit={save}><label className="pl-field">Judul<input className="pl-input" required maxLength={120} value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="pl-field">Penerima<select className="pl-input" value={target} onChange={e=>setTarget(e.target.value)}>{['All','Free','Pro','Unlimited'].map(t=><option key={t} value={t}>{t==='All'?'Semua pengguna':t}</option>)}</select></label><label className="pl-field">Pesan<textarea className="pl-input" required rows={5} maxLength={2000} value={content} onChange={e=>setContent(e.target.value)}/></label><button className="pl-btn pl-btn-primary" disabled={busy||!title.trim()||!content.trim()}><Send size={16}/>{busy?'Menyimpan...':editing.id?'Simpan perubahan':'Terbitkan pengumuman'}</button></form></Dialog>}
 </div>;
}
