import React, { useEffect, useState } from 'react';
import { Plus, Pencil, Trash2, Palette, SlidersHorizontal, Search, ToggleLeft, ToggleRight } from 'lucide-react';
import { Dialog, toast, confirmAction } from '@pixellift/ui';
import { adminApi } from '../services/api';
type Entry = {id:string;name:string;type?:string;value?:string;category?:string;settings?:any;isActive:boolean};
export function PresetsPage() {
 const [data,setData]=useState<{presets:Entry[];filters:Entry[]}>({presets:[],filters:[]}),[tab,setTab]=useState<'presets'|'filters'>('presets'),[search,setSearch]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const [editing,setEditing]=useState<Partial<Entry>|null>(null),[busy,setBusy]=useState(false);
 const [name,setName]=useState(''),[type,setType]=useState('solid'),[value,setValue]=useState('#8B5CF6'),[category,setCategory]=useState('Custom'),[brightness,setBrightness]=useState(0),[contrast,setContrast]=useState(0),[saturation,setSaturation]=useState(0);
 const load=async()=>{try{setData(await adminApi.getPresets());setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const edit=(entry:Partial<Entry>)=>{setEditing(entry);setName(entry.name||'');setType(entry.type||'solid');setValue(entry.value||'#8B5CF6');setCategory(entry.category||'Custom');setBrightness(entry.settings?.basic?.brightness||0);setContrast(entry.settings?.basic?.contrast||0);setSaturation(entry.settings?.color?.saturation||0);};
 const run=async(action:()=>Promise<any>,message:string)=>{setBusy(true);try{await action();toast.success(message);await load();}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!name.trim())return;await run(async()=>{
  const payload=tab==='presets'?{name:name.trim(),type,value}:{name:name.trim(),category,settings:{...editing?.settings,basic:{...editing?.settings?.basic,brightness,contrast},color:{...editing?.settings?.color,saturation}}};
  if(editing?.id){if(tab==='presets')await adminApi.updatePreset(editing.id,payload);else await adminApi.updateFilter(editing.id,payload);}
  else {if(tab==='presets')await adminApi.createPreset(payload);else await adminApi.createFilter(payload);}
  setEditing(null);
 },'Preset berhasil disimpan.');};
 const remove=async(entry:Entry)=>{if(await confirmAction('Hapus '+entry.name+'?'))await run(()=>tab==='presets'?adminApi.deletePreset(entry.id):adminApi.deleteFilter(entry.id),'Preset dihapus.');};
 const entries=data[tab].filter(p=>p.name.toLowerCase().includes(search.toLowerCase()));
 return <div className="admin-page"><div className="admin-page-heading"><div><span className="studio-eyebrow">CREATIVE LIBRARY</span><h1>Preset & filter</h1><p>Kelola latar dan gaya warna untuk studio pengguna.</p></div><button className="pl-btn pl-btn-primary" onClick={()=>edit({})}><Plus size={17}/>{tab==='presets'?'Tambah preset':'Tambah filter'}</button></div>
  <div className="admin-filterbar pl-card"><div className="admin-tabs"><button aria-pressed={tab==='presets'} onClick={()=>setTab('presets')}><Palette size={16}/>Background ({data.presets.length})</button><button aria-pressed={tab==='filters'} onClick={()=>setTab('filters')}><SlidersHorizontal size={16}/>Filter ({data.filters.length})</button></div><div className="admin-search-field"><Search size={16}/><input className="pl-input" aria-label="Cari preset" placeholder="Cari preset..." value={search} onChange={e=>setSearch(e.target.value)}/></div></div>
  {loading?<div className="pl-skeleton"/>:error?<div className="pl-empty"><p>{error}</p><button className="pl-btn" onClick={load}>Coba lagi</button></div>:!entries.length?<div className="pl-empty pl-card"><Palette size={36}/><h3>Belum ada preset yang cocok</h3><p>Tambahkan preset atau ubah pencarian.</p></div>:<div className="admin-preset-grid">{entries.map(p=><article className="pl-card admin-preset-card" key={p.id}><div className="admin-preset-preview" style={tab==='presets'?{background:p.value}:{background:'linear-gradient(135deg,#a5b4fc,#fbcfe8)',filter:'brightness('+(100+(p.settings?.basic?.brightness||0))+'%) contrast('+(100+(p.settings?.basic?.contrast||0))+'%) saturate('+(100+(p.settings?.color?.saturation||0))+'%)'}}>{tab==='filters'&&<SlidersHorizontal size={32}/>}</div><div className="pl-toolbar"><h3>{p.name}</h3><span className="pl-badge">{p.isActive?'Aktif':'Nonaktif'}</span></div><p className="pl-muted">{tab==='presets'?p.type:p.category}</p><div className="admin-card-actions"><button className="pl-btn" disabled={busy} onClick={()=>run(()=>tab==='presets'?adminApi.updatePreset(p.id,{isActive:!p.isActive}):adminApi.updateFilter(p.id,{isActive:!p.isActive}),'Status preset diperbarui.')} aria-label={(p.isActive?'Nonaktifkan ':'Aktifkan ')+p.name}>{p.isActive?<ToggleRight size={18}/>:<ToggleLeft size={18}/>}</button><button className="pl-icon-btn" aria-label={'Edit '+p.name} onClick={()=>edit(p)}><Pencil size={16}/></button><button className="pl-icon-btn" disabled={busy} aria-label={'Hapus '+p.name} onClick={()=>remove(p)}><Trash2 size={16}/></button></div></article>)}</div>}
  {editing&&<Dialog title={(editing.id?'Edit ':'Tambah ')+(tab==='presets'?'preset':'filter')} onClose={()=>{if(!busy)setEditing(null);}}><form className="pl-form" onSubmit={save}><label className="pl-field">Nama<input className="pl-input" required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label>
   {tab==='presets'?<><label className="pl-field">Jenis<select className="pl-input" value={type} onChange={e=>{setType(e.target.value);setValue(e.target.value==='solid'?'#8B5CF6':'linear-gradient(135deg, #6366f1, #ec4899)');}}><option value="solid">Warna solid</option><option value="gradient">Gradien</option></select></label><label className="pl-field">{type==='solid'?'Warna':'Gradien CSS'}<input className="pl-input" required value={value} onChange={e=>setValue(e.target.value)}/></label>{type==='solid'&&<input type="color" aria-label="Pilih warna" value={/^#[0-9a-f]{6}$/i.test(value)?value:'#8B5CF6'} onChange={e=>setValue(e.target.value)}/>}<div className="admin-preset-preview" style={{background:value}}/></>:<><label className="pl-field">Kategori<input className="pl-input" required value={category} onChange={e=>setCategory(e.target.value)}/></label>{[{label:'Brightness',value:brightness,set:setBrightness},{label:'Contrast',value:contrast,set:setContrast},{label:'Saturation',value:saturation,set:setSaturation}].map(f=><label className="pl-field" key={f.label}>{f.label}: {f.value}<input aria-label={f.label} type="range" min={-100} max={100} value={f.value} onChange={e=>f.set(Number(e.target.value))}/></label>)}</>}
   <div className="pl-dialog-actions"><button type="button" className="pl-btn" onClick={()=>setEditing(null)} disabled={busy}>Batal</button><button className="pl-btn pl-btn-primary" disabled={busy}>{busy?'Menyimpan...':'Simpan'}</button></div></form></Dialog>}
 </div>;
}
